services:
  jellysync:
    image: marrrrtthias/jellysync
    container_name: jellysync
    networks:
      - jellysync-nw
    environment:
      - FULL_REFRESH_ENDPOINT=http://jellyfin:8096/Library/Refresh
      - INCREMENTAL_ENDPOINT=http://jellyfin:8096/Library/Series/Added
      - JELLYFIN_API_KEY=your_api_key
      - POLL_INTERVAL=10
    volumes:
      - /volume2/jellysync:/jellysync

networks:
  jellysync-nw:
    internal: true